### ISSUE TITLE
Authentification context

### ISSUE THREAD

**Issue by bbenalia** [mhfortuna/react-shopping-cart-context#39]

**Comment by mhfortuna** [comment]
@all-contributors add @bbenalia for for code, design, ideas and projectManagement

**Comment by mhfortuna** [comment]
@all-contributors add @mhfortuna  for for code, design, ideas and projectManagement

**Comment by mhfortuna** [comment]
@all-contributors add @mhfortuna for for code, design, ideas and projectManagement
